version: '3.8'

services:
  rh-mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rh-dev-network

  rh-dev-server:
    image: peesadedu/rh-dev-server:latest
    ports:
      - "${SERVER_PORT}:80"
    environment:
      TZ: ${TZ}
    volumes:
      - rh-data:/app/data
    networks:
      - rh-dev-network
    depends_on:
      - rh-mysql


  rh-dev-dashboard:
    image: peesadedu/rh-dev-dashboard:latest
    container_name: dashboard-dev-container
    ports:
      - "5300:80"
    networks:
      - rh-dev-network
    depends_on:
      - rh-dev-server

networks:
  rh-dev-network:  
volumes:
  mysql-data:
  rh-data:
  
